<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-05-24T22:07:56-04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.timezone
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'True Blue Plumbing',
            'timezone' => 'America/Chicago',
        ],
    ],
];
